# Generated by Django 4.2.6 on 2024-01-27 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alapanyag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualiMennyiseg', models.IntegerField()),
                ('vastagsag_valaszt', models.IntegerField(choices=[(1, '0.5'), (2, '1.0'), (3, '1,5'), (4, '2.0'), (5, '2,5')])),
                ('meret_x_valaszt', models.IntegerField(choices=[(1, '1000'), (2, '1250'), (3, '1500')])),
                ('meret_y_valaszt', models.IntegerField(choices=[(1, '2000'), (2, '2500'), (3, '3000')])),
            ],
        ),
        migrations.CreateModel(
            name='Anyagtipus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anyagtipus', models.CharField(max_length=255)),
                ('anyagtipusa', models.IntegerField(choices=[(1, 'Aluminium'), (2, 'Horganyzott'), (3, 'Plexi'), (4, 'Rozsdamentes'), (5, 'Szenacél')])),
            ],
        ),
        migrations.CreateModel(
            name='Dolgozok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('beosztas', models.IntegerField(choices=[(1, 'Raktáros'), (2, 'Lézervágó')])),
            ],
        ),
        migrations.CreateModel(
            name='Megrendelesek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felhasznaltMennyiseg', models.IntegerField()),
                ('datumKezdes', models.DateField()),
                ('datumBefejezes', models.DateField()),
                ('alapanyag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raktar_app.alapanyag')),
                ('dolgozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raktar_app.dolgozok')),
            ],
        ),
        migrations.AddField(
            model_name='alapanyag',
            name='anyagtipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raktar_app.anyagtipus'),
        ),
    ]
