# Generated by Django 3.1.14 on 2024-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alapanyag',
            name='keszleten',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
