# Generated by Django 4.2.6 on 2024-01-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raktar_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alapanyag',
            old_name='aktualiMennyiseg',
            new_name='keszleten',
        ),
    ]
