# Generated by Django 3.1.14 on 2024-02-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolgozok',
            name='beosztas',
            field=models.CharField(choices=[('Raktáros', 'Raktáros'), ('Lézervágó', 'Lézervágó')], max_length=30),
        ),
    ]
