# Generated by Django 3.1.14 on 2024-02-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raktar_app', '0002_auto_20240217_0906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dolgozok',
        ),
    ]
