# Generated by Django 5.0.2 on 2024-03-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raktar_app', '0002_alter_alapanyag_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alapanyag',
            name='kiadasdatuma',
        ),
    ]
